### ISSUE TITLE
Accueil : Rajouter le cours actuel et le cours suivant

### ISSUE THREAD

**Issue by Sigeth** [JacksonKyoshi/n2i#1]
Sur la page Accueil, rajouter le cours actuel avec une barre de progression (petite barre en dessous du bloc), et le cours suivant en dessous avec quelques infos simples (heure + jour si ce n'est pas le jour actuel, prof, salle, intitulé de la matière)
S'il n'y a pas de cours actuellement, n'afficher que le cours suivant.

**Comment by Pierre-Gei** [comment]
Je suis dessus

**Comment by Pierre-Gei** [comment]
Done width #7
