### ISSUE TITLE
Absences :  parfois les absences renvoient : Error: FormatException: Unexpected character (at character 5) [{}][{}][{}]

### ISSUE THREAD

**Issue by Pierre-Gei** [JacksonKyoshi/n2i#8]
Étapes pour reproduire :

1. Se connecter 
2. clicker sur absences depuis le home screen

Il est possible que cela provienne d'avoir 0 absences.

De plus, le nombre de [{}] semble être aléatoire, dans mes tests, il a varié de 2 à 5 sans logique particulière.

**Comment by Sigeth** [comment]
Issue should have been fixed with the newest API version

**Comment by Pierre-Gei** [comment]
Still present x)
Maybe because i dont have absences

**Comment by Pierre-Gei** [comment]
My bad wrong branch
